clear;close all;clc;
%初始化
s=0;N=100000;i=1;%初始化计数值、阈值和循环变量
%%
%随机优化算法
while(s<N)
    U=ran d(1,2);%rand是产生0-1上的随机数
    x=2*(U(1)-0.5);y=U(2);
    %rand生成(0,1)上随机数,所以减去0.5再乘以2,就使得x变为(-1,1)上的随机数
    if(x^2+y^2<=1)%约束条件，不满足则直接进行下一次循环，重新生成随机数
        z=f2(x,y);%带入函数计算
        Z(i)=z;%将当前循环计算出函数值存入Z向量中
        maxz=max(Z);%计算当前循环Z向量最大值
        maxZ(i)=maxz;%将当前循环Y向量最大值存入向量maxZ中
        if(i==1)
            x0=x;y0=y;%第一次循环保存自变量
        else
            if(maxZ(i)>maxZ(i-1))%maxZ最新一次更新的值比前一次循环大
                %则认为找到一个更大的值，保存此次循环产生的自变量
                %同时计数值置0
                s=0;x0=x;y0=y;
            else
                s=s+1;%反之，计数值增1
            end
        end
        i=i+1;%有效循环次数增1
    end
end
%%
%输出结果
xmax=x0
ymax=y0
zmax=maxZ(end)%输出最大值及其对应x值
plot(maxZ,'k')%画出阶梯迭代图
xlabel('迭代次数')
ylabel('函数最大值变化')
title(['函数最大值为',num2str(zmax),',对应自变量为x=',num2str(xmax),',y=',num2str(ymax)])